language: node_js
node_js:
- 14
services:
- postgresql
addons:
  postgresql: '10'
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_install:
- openssl aes-256-cbc -K $encrypted_a0754f4bc6ef_key -iv $encrypted_a0754f4bc6ef_iv
  -in GOOGLE_APPLICATION_CREDENTIALS.json.enc -out GOOGLE_APPLICATION_CREDENTIALS.json
  -d
before_script:
- psql -c 'create database "stackathon-test";' -U postgres
script:
- npm test
- npm run build-client
deploy:
  skip_cleanup: true
  provider: heroku
  app: rescuerangers-1
  on:
    branch: travis-testing
  api_key:
    secure: 0TVcK5WPlzo6qFt8cdZ0YRyngIuBFnhBUSdFSgLiCt8RFJlykpE7SkyytY5kIJ9f0aKMWVS9CTA628CDNhWbv5wKTZ/CG1C+ERXhewPXeEX98CtGkuhJM3k0dO2YnTyDinSnkkuntIR2Ql3OrQwPHlOAPp1csLKpsyS4ILQf9PnYyv1EXki3Q7iOjqiY1UA4bK73++NH2prcqTcwv3qaVMH2WXA+WdHsxw+GrCxaSaRh39g3+gLYpsEUfObf1GvAXDXLyZexoDPRaJFHhdrkM1A+T6/kbvOIl5cwIOu6Yit4bihVNOWd60WMXy1BFvZgk4b4A99/yzDQcA8nPGcxIXtWQK+MFbA9CsjsNksnLc2PCJsITy33h131fNn0gMtjBhAlTD9tG4GfSWCk8hnIsT5V4UpzzAEmtWSlNqBt/L9bqnFlwdTtoG7JCAb4Ol+QJRTmOuaZjhVlVkmy4A9RllplX8JzNPub6wb9QtqodIv8xeAGvqQ/TWWY2CSi1YhJe9PLGe4eGKBiKTf3IYMPSjxhJvEcia4Sh25ekXKwHT1lJt9q3yJL3Ux4gdByEPdZXz9kqqHPQpAnG0bcbQT9baqoTBUDNlH3INTXTYpTqvL492UUhyMwP8unx2tS1mJFsudyJQmTCtBuN51oEGntPZs/AnSbpbvscDoDzG9hLO8=
